version: '3'
services:
  postgres:
    image: 'postgres:latest'
    container_name: strapi-postgres
    restart: unless-stopped
    networks:
      - strapi-net
    ports:
      - '5432:5432'
    expose:
      - '5432'
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    volumes:
      - 'strapi-postgres-data:~/volumes/data/strapi/db'
volumes:
  strapi-postgres-data:
    driver: local
networks:
  strapi-net:
    driver: bridge
